### ISSUE TITLE
 invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by forkposix** [JustTalDevelops/go-hcaptcha#23]
```
DEBU[0000] Verifying site configuration...              
INFO[0000] Requesting captcha...                        
no tasks in challenge, most likely ratelimited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x697369]

goroutine 1 [running]:
github.com/justtaldevelops/go-hcaptcha.(*Challenge).Solve(0x0, {0x7a09a0, 0x9c1da8})
	/home/user/go/pkg/mod/github.com/justtaldevelops/go-hcaptcha@v0.0.0-20220129051513-186a577d4a15/challenge.go:99 +0x49
main.token()
	/home/user/Documents/captcha/captcha.go:23 +0xb9
main.req()
	/home/user/Documents/captcha/captcha.go:60 +0x6f
main.main()
	/home/user/Documents/captcha/captcha.go:89 +0x17
exit status 2

```
do you have any idea ?

**Comment by JustTalDevelops** [comment]
Could you please attach the code used?

**Comment by JustTalDevelops** [comment]
Closing because of inactivity.
