### ISSUE TITLE
Is this library deprecated?

### ISSUE THREAD

**Issue by rushkii** [JustTalDevelops/go-hcaptcha#27]
Code:
```
package main

import (
	"fmt"
	"log"

	hcaptcha "github.com/justtaldevelops/go-hcaptcha"
)

func main() {
	c, err := hcaptcha.NewChallenge("coinsniper.net", "65cdfa64-8ed6-49f2-a8ba-f4fc8501e917")
	if err != nil {
		log.Panicln("Panic when NewChallenge: ", err)
	}
	err = c.Solve(&hcaptcha.GuessSolver{})
	if err != nil {
		log.Panicln("Panic when Solve: ", err)
	}
	fmt.Println(c.Token())
}

```

Errors:
```
2022/04/05 02:54:05 Downloading browsers...
2022/04/05 02:54:05 Downloaded browsers successfully
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/justtaldevelops/go-hcaptcha.NewChallenge({0x1050e86, 0x60}, {0x105baaf, 0x24}, {0x0, 0x0, 0xc0000bff70})
        C:/Users/UserName/go/pkg/mod/github.com/justtaldevelops/go-hcaptcha@v0.0.0-20220217211507-94eaf3df4933/challenge.go:89 +0x69c
main.main()
        D:/UserName/hCaptcha-solve/main.go:11 +0x3d
exit status 2
```

**Comment by mewzax** [comment]
replace `coinsniper.net` by `https://coinsniper.net` and it will work
![image](https://user-images.githubusercontent.com/75091300/168471087-309aa6b6-9b25-43fa-a7f3-e8336e333d10.png)

**Comment by rushkii** [comment]
> replace `coinsniper.net` by `https://coinsniper.net` and it will work ![image](https://user-images.githubusercontent.com/75091300/168471087-309aa6b6-9b25-43fa-a7f3-e8336e333d10.png)

Thank you so much!
